server:
  shutdown: graceful
  lifecycle:
    timeout-per-shutdown-phase: 1m
  port: 8080
  servlet:
    context-path: /
management:
  server:
    port: 8081
    base-path: /
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: io.builders-bank
  security:
    public-endpoints: /actuator/**;/v3/api-docs/**;/swagger-resources/**;/swagger-ui/*;/swagger-ui.html
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
springdoc:
  swagger-ui:
    path: /swagger-ui
    use-root-path: true
    disable-swagger-default-url: true
logging:
  level:
    ROOT: INFO